# Generated by Django 3.2.4 on 2021-06-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crul', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL_CONTAINER',
            new_name='LinkCONTAINER',
        ),
    ]
